canonical: http://hl7.org/fhir/us/sotus
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.sotus
name: USSOTUS
title: US Summary of the United States
status: active
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: sd
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 0
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
license: CC0-1.0
version: 0.0.1
copyrightYear: 2025+
releaseLabel: STU 1
publisher:
  name: HL7 International / Structured Douments
  url: http://www.hl7.org/Special/committees/structure
jurisdiction: 'urn:iso:std:iso:3166#US'
dependencies:
  hl7.fhir.uv.extensions.r4:
    version: 5.3.0-ballot-tc1
    uri: http://hl7.org/fhir/extensions/ImplementationGuide/hl7.fhir.uv.extensions
  hl7.fhir.uv.ips:
    version: current
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
  hl7.fhir.us.core:
    version: 8.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
menu:
  Home: index.html
  Table of Contents: toc.html
  The "SOTUS": Structure-of-the-SOTUS.html
  FHIR Artifacts:
    SOTUS Composition: StructureDefinition-Composition-us-sotus.html
    SOTUS Library (Profiles): profiles.html
  Support:
    About: IG-analysis.html
    Downloads: downloads.html
    Copyrights: copyrights.html
  Change Log: changes.html
resources:
  Bundle/bundle-no-info-required-sections:
    name: 'Bundle - No Info Required section'
    description: 'Bundle - No Info Required section'
    exampleCanonical: http://hl7.org/fhir/us/sotus/StructureDefinition/Bundle-us-sotus
